### ISSUE TITLE
I/O Improvements

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/DuAEF_Duik#214]
- [ ] Export to audition: Mac OS .sesx file name extension missing
- [x] export anim for all properties, see #86
- [x] import anim for all properties, see #86
- [x] import option: set values without anims too, and option for transform, effect, mask, shape content, see #86
- [x] import option: offset or in place #86
- [x] Better JSON export printing if possible
- [x] Better layer matching, see #82

**Comment by Nico-Duduf** [comment]
closing, moved to #225
