### ISSUE TITLE
Mac OS checklist

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/DuAEF_Duik#225]
A few things which must be tested and adjusted on Mac OS before release:

- [x] Dropdownlist: check if the popup window is truly borderless, find a way to make it if not
- [x] Fix network users #63 
- [x] Check file extension when exporting files, especially audition export #214 
- [x] Finish and test FFmpeg implementation for Mac OS
- [x] Alpha 10 bug on launch see http://forum.rainboxprod.coop/viewtopic.php?f=22&t=258&start=50#p932
